#!/usr/bin/with-contenv bash

# Install ZSH
echo "**** Adding packages to package install list ****"

echo "\
    zsh \
    htop \
    nmap \
    bat \
    tree \
    fzf \
    fd-find \
    cmake \
    make \
    wget \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv
    build-essential \
    libssl-dev \
    libffi-dev \
    traceroute \
    bc \
    vim \
    dialog \
    dnsutils \
    postgresql-client \
    podman \
    openssh-server \
    iproute2 \
    inetutils-ping \
    net-tools \
    podman-docker" >> /mod-repo-packages-to-install.list