#!/usr/bin/with-contenv bash

# Install ZSH
echo "**** Adding packages to package install list ****"

curl -fsSL "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh" \
  --output /usr/share/doc/fzf/examples/key-bindings.zsh --create-dirs

echo "\
    zsh \
    htop \
    nmap \
    bat \
    tree \
    fzf \
    fd-find \
    cmake \
    make \
    wget \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv
    build-essential \
    libssl-dev \
    libffi-dev \
    traceroute \
    bc \
    vim \
    dialog \
    dnsutils \
    postgresql-client \
    podman \
    openssh-server \
    podman-docker" >> /mod-repo-packages-to-install.list