#!/usr/bin/with-contenv bash

# Install ZSH
echo "**** Installing packages ****"

DEBIAN_FRONTEND=noninteractive && \
apt-get update && \
apt-get install -y \
    zsh htop nmap bat tree \
    fzf fd-find cmake make \
    wget python3 python3-pip \
    traceroute bc vim openssh-server \
    dialog dnsutils postgresql-client \
    ghostscript make biber \
    texlive-latex-extra texlive-lang-spanish && \
apt-get upgrade -y

echo "**** Install fzf zsh keybindings ****"
curl -fsSL "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh" \
  -o /usr/share/doc/fzf/examples/key-bindings.zsh
